version: '2'
services:
  mongo-db:
    build: .
    container_name: monguito
    ports:
      - "27017:27017"
    volumes:
      - /volumes/mongodb/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=tierras
